# Generated by Django 3.2.7 on 2021-09-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_employee_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pr_no',
            field=models.IntegerField(default=1),
        ),
    ]
