# Generated by Django 3.2.7 on 2021-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210921_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pr_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
